steps:
- uses: actions/checkout@v3
- uses: actions-for-kicad/setup-kicad@v1.0
  with:
    version: '8.0'
- uses: actions-for-kicad/generate-kicad-files@v1.0
  with:
    file: './GSE-Ignition-module.kicad_sch'
    type: 'schematic_pdf'
- name: Upload 
  uses: actions/upload-artifact@v3
  with:
    name: 'GSE-Ignition-module.pdf'
    path: './GSE-Ignition-module.pdf'
